global:

templates: 
- '/etc/alertmanager/template/*.tmpl'

route:
#  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: first-level-notifiers 
  routes:

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
# We use this to mute any warning-level notifications if the same alert is 
# already critical.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname', 'cluster', 'service']


receivers:
- name: 'first-level-notifiers'
  email_configs:
  - to: 'abc@gmail.com'
    send_resolved: true
    from: 'admin@prometheus.example.net'
    smarthost: 'email-smtp.XXX.amazonaws.com:25'
    auth_username: 'AAAAAAFASDIEN'
    auth_password: 'AAAADSDDNEIEVNEFALLEFOAINF'
  - to: 'xyz@example.net'
    send_resolved: true
    from: 'admin@prometheus.alarabiya.cc'
    smarthost: 'email-smtp.XXX.amazonaws.com:25'
    auth_username: 'AAAAAAFASDIEN'
    auth_password: 'AAAADSDDNEIEVNEFALLEFOAINF'
  slack_configs:
  - api_url: https://hooks.slack.com/services/AAAAAAAA/AAAAAAAQQQQAAAA
    send_resolved: true
    channel: '#prometheus-alerts'